name: Build and Push to GHCR for Nvidia

permissions:
  contents: read
  packages: write

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-base:
    name: Base Image
    uses: ./.github/workflows/image_base.yml
    with:
      flavor: nvidia
      platforms: linux/amd64
      dockerfile: Dockerfile.nvidia
    secrets: inherit

  build-app:
    name: App Image
    uses: ./.github/workflows/image_app.yml
    needs: build-base
    strategy:
      # Will build all images even if some fail.
      fail-fast: false
      matrix:
        include:
          - name: firefox
            platforms: linux/amd64
            dockerfile: Dockerfile.nvidia
          - name: brave
            platforms: linux/amd64
            dockerfile: Dockerfile.nvidia
          - name: chromium
            platforms: linux/amd64
            dockerfile: Dockerfile.nvidia
          - name: google-chrome
            platforms: linux/amd64
            dockerfile: Dockerfile.nvidia
          - name: microsoft-edge
            platforms: linux/amd64
            dockerfile: Dockerfile.nvidia
    with:
      name: ${{ matrix.name }}
      flavor: nvidia
      platforms: ${{ matrix.platforms }}
      dockerfile: ${{ matrix.dockerfile }}
    secrets: inherit
