name: Build and Push to GHCR

permissions:
  contents: read
  packages: write

on:
  schedule:
    - cron: '0 */3 * * *'
  push:
    branches:
      - custom
    paths:
      - 'runtime/**'
      - 'server/**'
      - 'client/**'
      - 'apps/**'
      - 'utils/**'
      - '.github/workflows/ghcr.yml'
      - '.github/workflows/image_base.yml'
      - '.github/workflows/image_app.yml'
      - '.github/workflows/client_build.yml'
  workflow_dispatch:

jobs:
  build-base:
    name: Base Image
    uses: ./.github/workflows/image_base.yml
    strategy:
      matrix:
        include:
          - flavor: ""
            dockerfile: Dockerfile
          - flavor: intel
            dockerfile: Dockerfile.intel
          - flavor: nvidia
            dockerfile: Dockerfile.nvidia
    with:
      flavor: ${{ matrix.flavor }}
      platforms: linux/amd64
      dockerfile: ${{ matrix.dockerfile }}
    secrets: inherit

  build-app:
    name: App Image (${{ matrix.name }}${{ matrix.flavor_suffix }})
    uses: ./.github/workflows/image_app.yml
    needs: build-base
    strategy:
      fail-fast: false
      matrix:
        include:
          # Default flavor
          - name: firefox
            flavor: ""
            flavor_suffix: ""
          - name: chromium
            flavor: ""
            flavor_suffix: ""
          - name: google-chrome
            flavor: ""
            flavor_suffix: ""
          - name: ungoogled-chromium
            flavor: ""
            flavor_suffix: ""
          - name: microsoft-edge
            flavor: ""
            flavor_suffix: ""
          - name: brave
            flavor: ""
            flavor_suffix: ""
          - name: vivaldi
            flavor: ""
            flavor_suffix: ""
          - name: opera
            flavor: ""
            flavor_suffix: ""
          - name: tor-browser
            flavor: ""
            flavor_suffix: ""
          - name: remmina
            flavor: ""
            flavor_suffix: ""
          - name: vlc
            flavor: ""
            flavor_suffix: ""
          - name: xfce
            flavor: ""
            flavor_suffix: ""
          - name: kde
            flavor: ""
            flavor_suffix: ""
          - name: desktop
            flavor: ""
            flavor_suffix: ""
          # Intel flavor
          - name: chromium
            flavor: intel
            flavor_suffix: ", intel"
          - name: google-chrome
            flavor: intel
            flavor_suffix: ", intel"
          - name: ungoogled-chromium
            flavor: intel
            flavor_suffix: ", intel"
          - name: microsoft-edge
            flavor: intel
            flavor_suffix: ", intel"
          - name: brave
            flavor: intel
            flavor_suffix: ", intel"
          - name: vivaldi
            flavor: intel
            flavor_suffix: ", intel"
          - name: opera
            flavor: intel
            flavor_suffix: ", intel"
          - name: tor-browser
            flavor: intel
            flavor_suffix: ", intel"
          - name: remmina
            flavor: intel
            flavor_suffix: ", intel"
          - name: vlc
            flavor: intel
            flavor_suffix: ", intel"
          - name: xfce
            flavor: intel
            flavor_suffix: ", intel"
          - name: kde
            flavor: intel
            flavor_suffix: ", intel"
          - name: desktop
            flavor: intel
            flavor_suffix: ", intel"
          # Nvidia flavor
          - name: firefox
            flavor: nvidia
            flavor_suffix: ", nvidia"
            dockerfile: Dockerfile.nvidia
          - name: brave
            flavor: nvidia
            flavor_suffix: ", nvidia"
            dockerfile: Dockerfile.nvidia
          - name: chromium
            flavor: nvidia
            flavor_suffix: ", nvidia"
            dockerfile: Dockerfile.nvidia
          - name: google-chrome
            flavor: nvidia
            flavor_suffix: ", nvidia"
            dockerfile: Dockerfile.nvidia
          - name: microsoft-edge
            flavor: nvidia
            flavor_suffix: ", nvidia"
            dockerfile: Dockerfile.nvidia
          - name: desktop
            flavor: nvidia
            flavor_suffix: ", nvidia"
            dockerfile: Dockerfile
    with:
      name: ${{ matrix.name }}
      flavor: ${{ matrix.flavor }}
      platforms: linux/amd64
      dockerfile: ${{ matrix.dockerfile || 'Dockerfile' }}
    secrets: inherit
