name: Build and Push to GHCR for Intel

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - custom
    paths:
      - 'runtime/Dockerfile.intel'
      - 'apps/**'
      - '.github/workflows/ghcr_intel.yml'
      - '.github/workflows/image_base.yml'
      - '.github/workflows/image_app.yml'
  workflow_dispatch:

jobs:
  build-base:
    name: Base Image
    uses: ./.github/workflows/image_base.yml
    with:
      flavor: intel
      platforms: linux/amd64
      dockerfile: Dockerfile.intel
    secrets: inherit

  build-app:
    name: App Image
    uses: ./.github/workflows/image_app.yml
    needs: build-base
    strategy:
      # Will build all images even if some fail.
      fail-fast: false
      matrix:
        include:
          - name: firefox
            platforms: linux/amd64
            dockerfile: Dockerfile.intel
          # Temporarily disabled due to Cloudflare blocked download link
          #- name: waterfox
          #  platforms: linux/amd64
          #  dockerfile: Dockerfile.intel
          - name: chromium
            platforms: linux/amd64
            dockerfile: Dockerfile.intel
          - name: google-chrome
            platforms: linux/amd64
            dockerfile: Dockerfile.intel
          - name: ungoogled-chromium
            platforms: linux/amd64
            dockerfile: Dockerfile.intel
          - name: microsoft-edge
            platforms: linux/amd64
            dockerfile: Dockerfile.intel
          - name: brave
            platforms: linux/amd64
            dockerfile: Dockerfile.intel
          - name: vivaldi
            platforms: linux/amd64
            dockerfile: Dockerfile.intel
          - name: opera
            platforms: linux/amd64
            dockerfile: Dockerfile.intel
          - name: tor-browser
            platforms: linux/amd64
            dockerfile: Dockerfile.intel
          - name: remmina
            platforms: linux/amd64
            dockerfile: Dockerfile.intel
          - name: vlc
            platforms: linux/amd64
            dockerfile: Dockerfile.intel
          - name: xfce
            platforms: linux/amd64
            dockerfile: Dockerfile.intel
          - name: kde
            platforms: linux/amd64
            dockerfile: Dockerfile.intel
    with:
      name: ${{ matrix.name }}
      flavor: intel
      platforms: ${{ matrix.platforms }}
      dockerfile: ${{ matrix.dockerfile }}
    secrets: inherit
